### ISSUE TITLE
User can like a cuisine photo

### ISSUE THREAD

**Issue by wirriamm** [wirriamm/ask-aunty#29]
**Any more specifics of this user story?**
User story 9
Backend for creating the polls instances

**What are the specific to-dos?**
Create a poll instance with meal_id, cuisine_id and user_id 
and the vote itself

**Any additional context or helpful breadcrumbs? 🍞**
to liase with @jasdang (user story 8)

**Comment by debwagon** [comment]
close #29 after merging w jasmine's file
