### ISSUE TITLE
User avatar not aligned

### ISSUE THREAD

**Issue by wirriamm** [wirriamm/ask-aunty#66]
**Describe the bug**
User avatar not aligned

**To Reproduce**

**Expected vs actual behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59186927/86205322-22b80900-bb9c-11ea-9a11-32ee93b3042e.png)

**Comment by wirriamm** [comment]
I am unable to stlye the avatar. Home is already aligned to the AskAunty logo on the left of the navbar. It is the avatar that needs to be aligned.

**Comment by debwagon** [comment]
deleting this ticket ya, cos no more home button, so no need to align
