### ISSUE TITLE
Meals show page

### ISSUE THREAD

**Issue by jasdang** [wirriamm/ask-aunty#78]
**Any more specifics of this user story?**

- [x] Route to show page
- [ ] After create meal, can share links via whatsapp (link to setup path)
- [ ] From meals index too, will direct to show page for that meal
- [ ] If can, fix the view results button
- [ ] Fix vanity id redirects 
- [ ] Link from meals index page

**What are the specific to-dos?**

**Any additional context or helpful breadcrumbs? 🍞**

**Comment by wirriamm** [comment]
@jasdang Further steps:
- From meals index too, will direct to show page for that meal
- Authentication: user can only access the meal show page if they have joined the meal
- Ensure that user can only click on "Start the poll" when the meal is still open
- After create meal, can share links via whatsapp (link to setup path)
I can help with the last one after you've cleared the rest
